// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobileslider.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class MobileSliderFlow
{
	private final IMendixObject mobileSliderFlowMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MobileSlider.MobileSliderFlow";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MobileSliderFlow_Car("MobileSlider.MobileSliderFlow_Car"),
		MobileSliderFlow_Account("MobileSlider.MobileSliderFlow_Account");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public MobileSliderFlow(IContext context)
	{
		this(context, Core.instantiate(context, "MobileSlider.MobileSliderFlow"));
	}

	protected MobileSliderFlow(IContext context, IMendixObject mobileSliderFlowMendixObject)
	{
		if (mobileSliderFlowMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MobileSlider.MobileSliderFlow", mobileSliderFlowMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MobileSlider.MobileSliderFlow");

		this.mobileSliderFlowMendixObject = mobileSliderFlowMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MobileSliderFlow.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mobileslider.proxies.MobileSliderFlow initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return mobileslider.proxies.MobileSliderFlow.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mobileslider.proxies.MobileSliderFlow initialize(IContext context, IMendixObject mendixObject)
	{
		return new mobileslider.proxies.MobileSliderFlow(context, mendixObject);
	}

	public static mobileslider.proxies.MobileSliderFlow load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return mobileslider.proxies.MobileSliderFlow.initialize(context, mendixObject);
	}

	public static java.util.List<mobileslider.proxies.MobileSliderFlow> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<mobileslider.proxies.MobileSliderFlow> result = new java.util.ArrayList<mobileslider.proxies.MobileSliderFlow>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MobileSlider.MobileSliderFlow" + xpathConstraint))
			result.add(mobileslider.proxies.MobileSliderFlow.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MobileSliderFlow_Car
	 */
	public final java.util.List<mobileslider.proxies.Car> getMobileSliderFlow_Car() throws CoreException
	{
		return getMobileSliderFlow_Car(getContext());
	}

	/**
	 * @param context
	 * @return value of MobileSliderFlow_Car
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mobileslider.proxies.Car> getMobileSliderFlow_Car(IContext context) throws CoreException
	{
		java.util.List<mobileslider.proxies.Car> result = new java.util.ArrayList<mobileslider.proxies.Car>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MobileSliderFlow_Car.toString());
		if (valueObject == null)
			return result;
		for (IMendixObject mendixObject : Core.retrieveIdList(context, (java.util.List<IMendixIdentifier>) valueObject))
			result.add(mobileslider.proxies.Car.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MobileSliderFlow_Car
	 * @param mobilesliderflow_car
	 */
	public final void setMobileSliderFlow_Car(java.util.List<mobileslider.proxies.Car> mobilesliderflow_car)
	{
		setMobileSliderFlow_Car(getContext(), mobilesliderflow_car);
	}

	/**
	 * Set value of MobileSliderFlow_Car
	 * @param context
	 * @param mobilesliderflow_car
	 */
	public final void setMobileSliderFlow_Car(IContext context, java.util.List<mobileslider.proxies.Car> mobilesliderflow_car)
	{
		java.util.List<IMendixIdentifier> identifiers = new java.util.ArrayList<IMendixIdentifier>();
		for (mobileslider.proxies.Car proxyObject : mobilesliderflow_car)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MobileSliderFlow_Car.toString(), identifiers);
	}

	/**
	 * @return value of MobileSliderFlow_Account
	 */
	public final usermanagement.proxies.Account getMobileSliderFlow_Account() throws CoreException
	{
		return getMobileSliderFlow_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of MobileSliderFlow_Account
	 */
	public final usermanagement.proxies.Account getMobileSliderFlow_Account(IContext context) throws CoreException
	{
		usermanagement.proxies.Account result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MobileSliderFlow_Account.toString());
		if (identifier != null)
			result = usermanagement.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MobileSliderFlow_Account
	 * @param mobilesliderflow_account
	 */
	public final void setMobileSliderFlow_Account(usermanagement.proxies.Account mobilesliderflow_account)
	{
		setMobileSliderFlow_Account(getContext(), mobilesliderflow_account);
	}

	/**
	 * Set value of MobileSliderFlow_Account
	 * @param context
	 * @param mobilesliderflow_account
	 */
	public final void setMobileSliderFlow_Account(IContext context, usermanagement.proxies.Account mobilesliderflow_account)
	{
		if (mobilesliderflow_account == null)
			getMendixObject().setValue(context, MemberNames.MobileSliderFlow_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MobileSliderFlow_Account.toString(), mobilesliderflow_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return mobileSliderFlowMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobileslider.proxies.MobileSliderFlow that = (mobileslider.proxies.MobileSliderFlow) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MobileSlider.MobileSliderFlow";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
